from position import Position

GAME_WINDOW_SIZE = 600
MARGIN_SIZE = 20
SCORE_SIZE = 80

WINDOW_SIZE = (GAME_WINDOW_SIZE + SCORE_SIZE + MARGIN_SIZE, GAME_WINDOW_SIZE + MARGIN_SIZE * 2)

GAME_WINDOW_START_POSITION = Position(SCORE_SIZE, MARGIN_SIZE)
GAME_WINDOW_FINAL_POSITION = Position(GAME_WINDOW_START_POSITION.x + GAME_WINDOW_SIZE, GAME_WINDOW_START_POSITION.y + GAME_WINDOW_SIZE)

BLOCK_SIZE = int(GAME_WINDOW_SIZE * 0.05)
